#!/usr/bin/env lua
local uci = require("luci.model.uci").cursor()
local aihelper = require("ai_chat_ctrl")

local request_method = os.getenv("REQUEST_METHOD")

print("Content-Type: text/plain\n")

if request_method == "POST" then

    local content_length = tonumber(os.getenv("CONTENT_LENGTH") or 0)
    local post_data = io.read(content_length)
    aihelper.prompt(post_data)
else
    io.write("This script only handles POST requests.")
end
