#!/bin/sh
#
# Usage:
#    root@OpenWrt:~# oasis_reflesh_install [mode]
#
# Description:
#   This script removes old versions of Oasis packages, installs new ones,
#   and restarts related services.
#
#   If you pass the keyword "migrate" as an argument, the script will:
#     1. Backup the current Oasis UCI configuration before removing packages.
#     2. Restore the configuration after the new installation.
#
# Examples:
#   oasis_reflesh_install
#       -> Normal update (no data migration).
#
#   oasis_reflesh_install migrate
#       -> Update with data migration (backup + restore).
#

MODE="$1"

# Backup configuration if migrate mode is enabled
if [ "$MODE" = "migrate" ]; then
    mkdir -p /tmp/oasis
    touch /tmp/oasis/backup
    uci export oasis > /tmp/oasis/backup
    cp -r /etc/oasis/oasis.conf /tmp/oasis/oasis.conf
fi

opkg update

# Remove tool plugins
opkg remove oasis-tool-test
opkg remove oasis-tool-wireguard

# Remove old versions
opkg remove luci-i18n-oasis-ja
opkg remove oasis-tool-analysis
opkg remove oasis-tool-template
opkg remove oasis-tool-wireguard
opkg remove oasis-tool-test
opkg remove oasis-tool-edge
opkg remove luci-app-oasis
opkg remove oasis-mod-test
opkg remove oasis-mod-agent
opkg remove oasis-mod-tool
opkg remove oasis-mod-retired
opkg remove oasis

# Install new versions
opkg install oasis_3.2.6-r1_all.ipk
opkg install luci-app-oasis_3.2.6-r1_all.ipk
opkg install oasis-mod-tool_1.1.1-r1_all.ipk
opkg install oasis-mod-agent_1.0.0-r1_all.ipk
opkg install oasis-mod-retired_1.0.0-r1_all.ipk
opkg install oasis-tool-edge_1.0.0-r1_all.ipk
opkg install oasis-mod-test_1.0.0-r1_all.ipk

# Restore configuration if migrate mode is enabled
if [ "$MODE" = "migrate" ]; then
    uci -f /tmp/oasis/backup import oasis
    cp -r /tmp/oasis/oasis.conf /etc/oasis/oasis.conf
fi

# Restart services
service olt_tool restart
service rpcd restart
