#!/usr/bin/env lua
local jsonc = require("luci.jsonc")
local uci = require("luci.model.uci").cursor()
local oasis = require("oasis.chat.ctrl")
local filter = require("oasis.chat.filter")

local request_method = os.getenv("REQUEST_METHOD")

print("Content-Type: text/plain\n")

-- os.execute("echo \"oasis cgi called\" >> /tmp/oasis.log")

if request_method == "POST" then
    -- os.execute("echo POST >> /tmp/oasis.log")
    local content_length = tonumber(os.getenv("CONTENT_LENGTH") or 0)
    local post_data = io.read(content_length)
    -- os.execute("echo " .. content_length .. " >> /tmp/oasis.log")
    -- os.execute("echo " .. post_data.message .. " >> /tmp/oasis.log")

    local json_tbl = jsonc.parse(post_data)

    -- for k, v in pairs(json_tbl) do
    --     os.execute("key:" .. k .. ", value = " .. v .. " >> /tmp/oasis.log")
    -- end

    if not json_tbl then
        io.write("Message Format Error.")
        return
    end

    local text = oasis.output(json_tbl)
    local json = {}
    json.uci_list = filter.uci_cmd_filter(text)
    -- json.uci_list.exist = filter.check_uci_cmd_item(json.uci_list)
    json.uci_list = jsonc.stringify(json, false)
    if json.uci_list then
        os.execute("echo \"" .. json.uci_list .. "\" >> /tmp/oasis.log")
        -- io.write(json.uci_list)
    else
        os.execute("echo \"no uci list\" >> /tmp/oasis.log")
    end
else
    io.write("This script only handles POST requests.")
end
