include $(TOPDIR)/rules.mk

PKG_NAME:=oasis-tool-maker
PKG_VERSION:=1.0.0
PKG_RELEASE:=1

include $(INCLUDE_DIR)/package.mk

define Package/oasis-tool-maker
    CATEGORY:=utakamo
    SECTION:=utakamo
    TITLE:= Oasis Local Tool Maker
    DEPENDS:=+oasis-mod-tool
    PKGARCH:=all
endef

define Build/Compile
endef

define Package/oasis-tool-maker/install
endef

$(eval $(call BuildPackage,oasis-tool-maker))
